[workspace]

members = [
    "vsprofile",
    "ctypes",
    "skse64",
    "versionlib",
    "SkyrimUncapper"
]

[profile.release]
opt-level = 'z'

[profile.dev]
# O0 is just impossible to read.
opt-level = 1
