[workspace]

members = [
    "disarray",
    "later",
    "racy_cell",
    "skse64_common",
    "skse64",
    "versionlib",
    "skyrim_patcher",
    "vdb-dump",
    "SkyrimUncapper"
]

[profile.release]
panic = "abort"
debug = false
incremental = false
opt-level = 'z'

[profile.dev]
panic = "abort"
debug = true
incremental = false
# O0 is just impossible to read.
opt-level = 1
