[package]
name = "SkyrimUncapper"
version = "2.1.5"
edition = "2021"

[lib]
name = "SkyrimUncapper"
crate-type = ["cdylib"]

[features]
alloc_trampoline = ["skyrim_patcher/alloc_trampoline"]

[dependencies]
racy_cell = { path = "../lib/racy_cell" }
configparser = "3.0.2"
later = { path = "../lib/later" }
disarray = { path = "../lib/disarray" }
skse64 = { path = "../lib/skse64" }
skyrim_patcher = { path = "../lib/skyrim_patcher" }

[build-dependencies]
winres = "0.1.12"
embed-resource = "1.8.0"
cc = "1.0.79"
