[package]
name = "SkyrimUncapper"
version = "2.0.1"
edition = "2021"

[lib]
name = "SkyrimUncapper"
crate-type = ["cdylib"]

[features]
alloc_trampoline = ["skyrim_patcher/alloc_trampoline"]
by_offset = ["skyrim_patcher/by_offset"]

[dependencies]
configparser = "3.0.2"
later = { path = "../later" }
disarray = { path = "../disarray" }
skse64 = { path = "../skse64" }
skyrim_patcher = { path = "../skyrim_patcher", features = [ "alloc_trampoline" ] }

[build-dependencies]
winres = "0.1.12"
