[package]
name = "SkyrimUncapper"
version = "2.0.0"
edition = "2021"

[lib]
name = "SkyrimUncapper"
crate-type = ["cdylib"]

[dependencies]
rust-ini = "0.18.0"
once_cell = "1.17.0"
libc = "0.2.139"
ctypes = { path = "../ctypes" }
disarray = { path = "../disarray" }
skse64 = { path = "../skse64" }
versionlib = { path = "../versionlib" }

[build-dependencies]
winres = "0.1.12"
cc = "1.0.78"
