[package]
name    = "SkyrimUncapper"
version = "2.2.3"
edition = "2021"

[lib]
name       = "SkyrimUncapper"
crate-type = ["cdylib"]

[dependencies]
core-util = { path = "../lib/core-util" }
libskyrim = { path = "../lib/libskyrim" }

[build-dependencies]
winres         = "0.1.12"
