[package]
name = "SkyrimUncapper"
version = "2.2.0"
edition = "2021"

[lib]
name = "SkyrimUncapper"
crate-type = ["cdylib"]

[dependencies]
racy_cell = { path = "../lib/racy_cell" }
deflate = { path = "../lib/deflate" }
plugin_ini = { path = "../lib/plugin_ini" }
later = { path = "../lib/later" }
disarray = { path = "../lib/disarray" }
skse64 = { path = "../lib/skse64" }
skyrim_patcher = { path = "../lib/skyrim_patcher" }

[build-dependencies]
winres = "0.1.12"
embed-resource = "1.8.0"
cc = "1.0.79"
deflate = { path = "../lib/deflate" }
