[package]
name = "SkyrimUncapper"
version = "2.0.0"
edition = "2021"

[lib]
name = "SkyrimUncapper"
crate-type = ["cdylib"]

[dependencies]
configparser = "3.0.2"
later = { path = "../later" }
ctypes = { path = "../ctypes" }
disarray = { path = "../disarray" }
skse64 = { path = "../skse64" }
skyrim_patcher = { path = "../skyrim_patcher" }

[build-dependencies]
winres = "0.1.12"
vsprofile = { path = "../vsprofile" }
