[package]
name = "skyrim_uncapper"
version = "2.0.0"
edition = "2021"

[lib]
name = "SkyrimUncapper"
crate-type = ["cdylib"]

[dependencies]
dirs-next = "2.0.0"
rust-ini = "0.18.0"
ctypes = { path = "../ctypes" }
skse64 = { path = "../skse64" }
versionlib = { path = "../versionlib" }
