[package]
name = "versionlib"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[[bin]]
path = "main.rs"
name = "vdb-dump"
required-features = [ "dump" ]

[features]
by_offset = []
dump = [ "skse64/disas", "skse64/not_plugin" ]

[dependencies]
skse64 = { path = "../skse64" }
