[package]
name = "skyrim_patcher"
version = "1.0.5"
edition = "2021"

[features]
alloc_trampoline = ["skse64/trampoline"]

[dependencies]
skse64 = { path = "../skse64" }
versionlib = { path = "../versionlib" }
